Stop building/installing on hook error.

diff --git a/src/lib/pkgbuild.sh.in b/src/lib/pkgbuild.sh.in
--- a/src/lib/pkgbuild.sh.in
+++ b/src/lib/pkgbuild.sh.in
@@ -59,18 +59,23 @@ source_makepkg_conf() {
 # Add hooks for aur packages
 # Put scripts into aur_hooks_dir.
 # I'll call scripts like: ./google-chrome.hook pre-build
-#                         ./google-chrome.hook post-build
+#                         ./google-chrome.hook post-build success
+#                         ./google-chrome.hook post-build fail
 #                         ./google-chrome.hook pre-install
 #                         ./google-chrome.hook post-install success
 #                         ./google-chrome.hook post-install fail
-# Call: run_hook <pkg name> <args...>
+# Usage: run_hook <pkg name> <args...>
+# Return 1 on failure, 0 on success (or hook not exists)
 run_hook () {
 	_sh_pos="$aur_hooks_dir/$1.hook"
-	if [ ! -f $_sh_pos ]; then
-		return 0
-	fi
+	[[ ! -f $_sh_pos ]] && return 0
 	echo "Running $2 hook..."
 	$_sh_pos $2 $3
+	_ret=$?
+	if [ $_ret -ne 0 ]; then
+		echo "Error: Hook script returns $_ret"
+		return 1
+	fi
 }
 
 # Read PKGBUILD
@@ -363,13 +368,13 @@ install_package() {
 		esac
 	done
 	(( ! failed )) &&
-		run_hook $pl_pkgname 'pre-install' &&
+		run_hook $pl_pkgname 'pre-install' && _pre_inst_hook_done=1 &&
 		su_pacman -U $SP_ARG "${PACMAN_U_ARG[@]}" "${PACMAN_S_ARG[@]}" "$YPKGDEST"/!(*.sig) ||
 		failed=$?
 	if (( failed )); then
 		warning $(_gettext "Your packages are saved in %s" "$YAOURTTMPDIR")
 		cp -i "$YPKGDEST"/* $YAOURTTMPDIR/ || warning $(_gettext 'Unable to copy packages to %s directory' "$YAOURTTMPDIR")
-		run_hook $pl_pkgname 'post-install' 'fail'
+		(( $_pre_inst_hook_done )) && run_hook $pl_pkgname 'post-install' 'fail'
 	else
 		run_hook $pl_pkgname 'post-install' 'success'
 	fi
@@ -414,8 +419,7 @@ package_loop() {
 		edit_pkgbuild $default_answer || { failed=1; break; }
 		prompt "$(_gettext 'Continue building %s ? ' "$pl_pkgname")$(yes_no 1)"
 		builduseragrees || { failed=1; break; }
-		run_hook $pl_pkgname 'pre-build'
-		build_package
+		run_hook $pl_pkgname 'pre-build' &&	build_package
 		ret=$?
 		case "$ret" in
 			0|2) break ;;
@@ -426,7 +430,9 @@ package_loop() {
 			*) return 99 ;; # should never execute
 		esac
 	done
-	run_hook $pl_pkgname 'post-build'
+	(( ! failed )) && _build_status='success' || _build_status='fail'
+	run_hook $pl_pkgname 'post-build' $_build_status
+	(( ! failed )) && failed=$? # Got hook return val
 	(( ! ret )) && (( ! failed )) &&
 	  ( [[ $MAJOR == "pkgbuild" ]] && (( INSTALL_FLAG )) || ! [[ $MAJOR == "pkgbuild" ]] ) &&
 	    { install_package || failed=1; }
@@ -547,3 +553,4 @@ package_pkgbuild_only() {
 source_makepkg_conf
 
 # vim: set ts=4 sw=4 noet:
+
